### ISSUE TITLE
PLL discriminator logic

### ISSUE THREAD

**Issue by Priyanka2092** [perrysou/GNSS_SDR#2]
Hello,

I have a doubt in the step where you are mixing the incoming signal to baseband. As in you are using cosine carrier to Q channel and sine carrier to I channel as given below:
            % First mix to baseband
            qBasebandSignal = carrCos .* rawSignal;
            iBasebandSignal = carrSin .* rawSignal;

and later in PLL discriminator you are using Q/I which will in this case become Cosine/Sine. 

Then how is it possible to take atan of this value here to get the desired result?

Also everywhere in books as well its written as the Phi=tan(Q/I) which is only possible if it is sin(theta)/cos(theta).

Kindly explain me the logic behind this and I'll be very grateful to you.

Thanks,
Priyanka

**Comment by perrysou** [comment]
The phase difference between I and Q signals is +pi / 2, meaning that if I = sin(2*pi*f*t), Q = sin(2*pi*f*t + pi / 2) = cos(2*pi*f*t), hence the first two lines of code. However, the phase difference theta (or psi defined in eq 7.19 in the textbook) is different from 2*pi*f*t.
